=== MichaelGrafnetter/active-directory-firewall/ADCS/CAFWTool/Set-ADCSFirewallPolicy.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "Schema file for the Set-ADCSFirewallPolicy.json config.",
    "title": "Certification Authority Firewall Configuration",
    "type": "object",
    "properties": {
      "GroupPolicyObjectName": {
        "type": "string",
        "default": "Certification Authority Firewall",
        "description": "The name of the Group Policy Object (GPO) that will be created or updated."
      },
      "GroupPolicyObjectComment": {
        "type": "string",
        "default": "This GPO is managed by the Set-ADDSFirewallPolicy.ps1 PowerShell script.",
        "description": "The comment that will be added to the Group Policy Object (GPO)."
      },
      "TargetDomain": {
        "type": "string",
        "default": null,
        "examples": [ "contoso.com" ],
        "description": "The domain in which the Group Policy Object (GPO) will be created or updated. This setting is only useful in multi-domain forests. If not specified, the script will attempt to determine the domain of the current user."
      },
      "LogDroppedPackets": {
        "type": "boolean",
        "default": false,
        "description": "Indicates whether the packets dropped by the firewall should be logged."
      },
      "LogAllowedPackets": {
        "type": "boolean",
        "default": false,
        "description": "Indicates whether the packets allowed by the firewall should be logged."
      },
      "LogFilePath": {
        "type": "string",
        "default": "%systemroot%\\system32\\logfiles\\firewall\\pfirewall.log",
        "description": "The path to the log file that will be used to store information about the allowed and/or dropped packets."
      },
      "LogMaxSizeKilobytes": {
        "type": "integer",
        "minimum": 1,
        "maximum": 32767,
        "default": 32767,
        "description": "The maximum size of the firewall log file in kilobytes."
      },
      "ClientAddresses": {
        "oneOf": [
          {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "examples": [
                    "10.220.1.0/24",
                    "10.220.2.100-10.220.2.150",
                    "2001:db8:abcd:0012::0/64"
                  ]
                },
                {
                  "enum": [
                    "LocalSubnet",
                    "DNS",
                    "DHCP",
                    "WINS",
                    "DefaultGateway",
                    "Internet",
                    "Intranet",
                    "IntranetRemoteAccess",
                    "PlayToDevice",
                    "CaptivePortal"
                  ]
                }
              ],
              "minLength": 1,
              "uniqueItems": true
            }
          },
          {
            "type": "array",
            "items": {
              "const": "Any",
              "minLength": 1,
              "maxLength": 1
            }
          }
        ],
        "default": [ "Any" ],
        "description": "List of client IP adresses from which inbound traffic should be allowed."
      },
      "ManagementAddresses": {
        "oneOf": [
          {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "examples": [
                    "10.220.1.0/24",
                    "10.220.2.100-10.220.2.150",
                    "2001:db8:abcd:0012::0/64"
                  ]
                },
                {
                  "enum": [
                    "LocalSubnet",
                    "DNS",
                    "DHCP",
                    "WINS",
                    "DefaultGateway",
                    "Internet",
                    "Intranet",
                    "IntranetRemoteAccess",
                    "PlayToDevice",
                    "CaptivePortal"
                  ]
                }
              ],
              "minLength": 1,
              "uniqueItems": true
            }
          },
          {
            "type": "array",
            "items": {
              "const": "Any",
              "minLength": 1,
              "maxLength": 1
            }
          }
        ],
        "default": [ "Any" ],
        "description": "List of IP addresses from which inbound management traffic should be allowed."
      },
      "DomainControllerAddresses": {
        "oneOf": [
          {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "examples": [
                    "10.220.1.0/24",
                    "10.220.2.100-10.220.2.150",
                    "2001:db8:abcd:0012::0/64"
                  ]
                },
                {
                  "enum": [
                    "LocalSubnet",
                    "DNS",
                    "DHCP",
                    "WINS",
                    "DefaultGateway",
                    "Internet",
                    "Intranet",
                    "IntranetRemoteAccess",
                    "PlayToDevice",
                    "CaptivePortal"
                  ]
                }
              ],
              "minLength": 1,
              "uniqueItems": true
            }
          },
          {
            "type": "array",
            "items": {
              "const": "Any",
              "minLength": 1,
              "maxLength": 1
            }
          }
        ],
        "default": [ "Any" ],
        "description": "List of domain controller IP addresses, between which replication and management traffic will be allowed."
      },
      "RadiusClientAddresses": {
        "oneOf": [
          {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string",
                  "examples": [
                    "10.220.1.0/24",
                    "10.220.2.100-10.220.2.150",
                    "2001:db8:abcd:0012::0/64"
                  ]
                },
                {
                  "enum": [
                    "LocalSubnet",
                    "DNS",
                    "DHCP",
                    "WINS",
                    "DefaultGateway",
                    "Internet",
                    "Intranet",
                    "IntranetRemoteAccess",
                    "PlayToDevice",
                    "CaptivePortal"
                  ]
                }
              ],
              "minLength": 1,
              "uniqueItems": true
            }
          },
          {
            "type": "array",
            "items": {
              "const": "Any",
              "minLength": 1,
              "maxLength": 1
            }
          }
        ],
        "default": [ "Any" ],
        "description": "List of RADIUS client IP adresses from which inbound traffic should be allowed."
      },
      "NtdsStaticPort": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1024,
            "maximum": 49151,
            "examples": [ 38901 ]
          },
          {
            "const": 0
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Static port to be used for inbound Active Directory RPC traffic."
      },
      "NetlogonStaticPort": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1024,
            "maximum": 49151,
            "examples": [ 38902 ]
          },
          {
            "const": 0
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Static port to be used for inbound Netlogon traffic."
      },
      "DfsrStaticPort": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1024,
            "maximum": 49151,
            "examples": [ 5722 ]
          },
          {
            "const": 0
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Static port to be used for DFSR traffic."
      },
      "FrsStaticPort": {
        "oneOf": [
          {
            "type": "integer",
            "minimum": 1024,
            "maximum": 49151,
            "examples": [ 38903 ]
          },
          {
            "const": 0
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Static port to be used for legacy FRS traffic."
      },
      "WmiStaticPort": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether WMI traffic should use a static port."
      },
      "RestrictADWS": {
        "type": "boolean",
        "default": false,
        "description": "Indicates whether the Active Directory Web Services (ADWS) should only be available from management IPs."
      },
      "DisableNetbiosBroadcasts": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether the NetBIOS protocol should be switched to P-node (point-to-point)."
      },
      "DisableLLMNR": {
        "type": "boolean",
        "default": false,
        "description": "Indicates whether the Link-Local Multicast Name Resolution (LLMNR) client should be disabled."
      },
      "DisableMDNS": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether the Multicast DNS (mDNS) client should be disabled."
      },
      "BlockManagementFromDomainControllers": {
        "type": "boolean",
        "default": false,
        "description": "Indicates whether management traffic from other domain controllers should be blocked."
      },
      "EnableServiceManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote service management should be enabled."
      },
      "EnableEventLogManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote event log management should be enabled."
      },
      "EnableScheduledTaskManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote scheduled task management should be enabled."
      },
      "EnableWindowsRemoteManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Windows Remote Management traffic should be enabled."
      },
      "EnablePerformanceLogAccess": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote performance log access should be enabled."
      },
      "EnableOpenSSHServer": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound OpenSSH traffic should be enabled."
      },
      "EnableRemoteDesktop": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Remote Desktop traffic should be enabled."
      },
      "EnableDiskManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote disk management should be enabled."
      },
      "EnableBackupManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote backup management should be enabled."
      },
      "EnableFirewallManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether remote firewall management should be enabled."
      },
      "EnableComPlusManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound COM+ management traffic should be enabled."
      },
      "EnableLegacyFileReplication": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound legacy file replication traffic should be enabled."
      },
      "EnableNetbiosNameService": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound NetBIOS Name Service should be allowed."
      },
      "EnableNetbiosDatagramService": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound NetBIOS Datagram Service traffic should be allowed."
      },
      "EnableNetbiosSessionService": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound NetBIOS Session Service (NBSS) traffic should be allowed."
      },
      "EnableWINS": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Windows Internet Name Service (WINS) traffic should be allowed."
      },
      "EnableDhcpServer": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Dynamic Host Configuration Protocol (DHCP) server traffic should be allowed."
      },
      "EnableNPS": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Network Policy Server (NPS) / RADIUS traffic should be allowed."
      },
      "EnableKMS": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Key Management Service (KMS) traffic should be allowed."
      },
      "EnableWSUS": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Windows Server Update Services (WSUS) traffic should be allowed."
      },
      "EnableWDS": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Windows Deployment Services (WDS) traffic should be allowed."
      },
      "EnableWebServer": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound http.sys-based web server traffic on default HTTP and HTTPS ports should be allowed."
      },
      "EnableFSRMManagement": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound File Server Resource Manager (FSRM) management traffic should be allowed."
      },
      "EnablePrintSpooler": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether inbound Print Spooler traffic through RPC over TCP should be allowed."
      },
      "EnableNetworkProtection": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether the Network protection feature of Microsoft Defender Antivirus should be enabled."
      },
      "BlockWmiCommandExecution": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether to block process creations originating from PSExec and WMI commands using Defender ASR."
      },
      "EnableRpcFilters": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Indicates whether additional filtering of RPC over Named Pipes should be applied."
      },
      "EnableLocalIPsecRules": {
        "type": "boolean",
        "default": true,
        "description": "Indicates whether local IPSec rules should be enabled."
      },
      "CustomRuleFileNames": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          }
        ],
        "default": null,
        "examples": [ ["CustomRules.BackupAgent.ps1", "CustomRules.ManagementAgent.ps1"] ],
        "description": "Specifies the name(s) of additional script file(s) containing firewall rules that will be imported into the Group Policy Object (GPO)."
      }
    },
    "required": [
      "GroupPolicyObjectName",
      "DomainControllerAddresses",
      "ManagementAddresses",
      "ClientAddresses"
    ]
  }

=== MichaelGrafnetter/active-directory-firewall/ADCS/CAFWTool/Set-ADCSFirewallPolicy.Sample.json
{
    "$schema": "Set-ADCSFirewallPolicy.schema.json",
    "GroupPolicyObjectName": "Certification Authority Firewall",
    "GroupPolicyObjectComment": "This GPO is managed by the Set-ADCSFirewallPolicy.ps1 PowerShell script.",
    "TargetDomain": "contoso.com",
    "LogDroppedPackets": true,
    "LogAllowedPackets": false,
    "LogFilePath": "%systemroot%\\system32\\logfiles\\firewall\\pfirewall.log",
    "LogMaxSizeKilobytes": 128,
    "ClientAddresses": [ "10.220.2.0/24", "10.220.4.0/24", "10.220.5.0/24", "10.220.6.0/24" ],
    "ManagementAddresses": [ "10.220.3.0/24" ],
    "DomainControllerAddresses": [ "10.220.1.0/24" ],
    "RadiusClientAddresses": [ "10.220.1.12/32", "10.220.1.13/32" ],
    "NtdsStaticPort": 38901,
    "NetlogonStaticPort": 38902,
    "FrsStaticPort": 38903,
    "DfsrStaticPort": 5722,
    "WmiStaticPort": true,
    "RestrictADWS": true,
    "DisableNetbiosBroadcasts": true,
    "DisableLLMNR": true,
    "DisableMDNS": true,
    "BlockManagementFromDomainControllers": false,
    "EnableServiceManagement": true,
    "EnableEventLogManagement": true,
    "EnableScheduledTaskManagement": true,
    "EnableWindowsRemoteManagement": true,
    "EnablePerformanceLogAccess": true,
    "EnableOpenSSHServer": false,
    "EnableRemoteDesktop": true,
    "EnableDiskManagement": true,
    "EnableBackupManagement": true,
    "EnableFirewallManagement": false,
    "EnableComPlusManagement": true,
    "EnableLegacyFileReplication": false,
    "EnableNetbiosNameService": false,
    "EnableNetbiosDatagramService": false,
    "EnableNetbiosSessionService": false,
    "EnableWINS": false,
    "EnableDhcpServer": false,
    "EnableNPS": false,
    "EnableKMS": false,
    "EnableWSUS": false,
    "EnableWDS": false,
    "EnableWebServer": false,
    "EnableFSRMManagement": false,
    "EnablePrintSpooler": false,
    "EnableNetworkProtection": true,
    "BlockWmiCommandExecution": true,
    "EnableRpcFilters": true,
    "EnableLocalIPsecRules": false,
    "CustomRuleFileNames": null
}
